[package]
name = "gui_test"
version = "0.1.0"
authors = ["Roman Uvarov <uvarovrs40@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.0.14"
image = "0.23.14"

[profile.dev]
opt-level = 1